# -*- coding: utf-8 -*-
"""aula3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NilhGzBtWJ6wanJhp47Y4113VSp063LI
"""

#Desafio
#Crie um sistema de calculadora
#concatenar as saídas
#SOMA | DIVISÃO | MULTIPLICAÇÃO | SUBSTRAÇÃO
#UTILIZAR input() - print() -  +|-|/ |**|*|//

print('Calculadora')

n1 = float(input('Digite um número> '))
n2 = float(input('Digite um número> '))

soma = n1 + n2
subtrair = n1 -n2
multiplicar  = n1*n2
dividir  = n1/n2
dividir2 =  n1// n2
potencia =  n1**n2

print(f'''
Resultado da soma = {soma}
Resultado da divisão  =  {dividir}
Resultado da subtração = {subtrair}
Resultado da multiplicação = {multiplicar}
Resultado da potencia = {potencia}
Resultado da divisão2 = {dividir2}
''')